# Generated by Django 5.1.3 on 2024-11-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_stream_rest', '0002_add_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='amenities_preference',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='nonstop_preference',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='number_of_adults',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='travel_budget',
        ),
        migrations.AddField(
            model_name='reservation',
            name='adults',
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='destination',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='traveling_from',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=31),
        ),
    ]
