# Generated by Django 5.1.3 on 2024-12-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_stream_rest', '0003_update_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='infants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['name'], name='app_reserva_name_c561a3_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['name', 'email'], name='app_reserva_name_4824c2_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['phone'], name='app_reserva_phone_0e0b04_idx'),
        ),
    ]
