# Generated by Django 5.1.3 on 2024-12-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_stream_rest', '0004_update_reservation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reservation',
            name='app_reserva_name_c561a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='app_reserva_phone_0e0b04_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='travel_stre_name_575e5c_idx',
            old_name='app_reserva_name_4824c2_idx',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(db_index=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(db_index=True, max_length=31),
        ),
    ]
