# fly.toml app configuration file generated for travel-stream on 2025-02-25T10:44:48-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'travel-stream'
primary_region = 'lax'
console_command = "/app/manage.py shell"

[build]

[env]
  PORT = "8000"
  DEBUG = false
  ALLOWED_HOSTS = "api.travelstreamapp.com,travel-stream.fly.dev"
  CORS_ALLOWED_ORIGINS = "https://travelstreamapp.com"
  CSRF_TRUSTED_ORIGINS = "https://travelstreamapp.com"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "512"
  cpu_kind = "shared"
  cpus = 1

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"
