# Generated by Django 5.1.3 on 2024-11-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('number_of_adults', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
                ('infants', models.PositiveIntegerField()),
                ('nonstop_preference', models.BooleanField()),
                ('travel_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amenities_preference', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
