name: Check JavaScript Linting
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "frontend/**/*.ts"
      - "frontend/**/*.tsx"
      - "frontend/**/*.js"
      - "frontend/**/*.jsx"
      - "frontend/**/*.json"
      - ".github/workflows/check-javascript-lint.yaml"
jobs:
  eslint:
    runs-on: ubuntu-latest
    container: node:22-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Run ESLint
        working-directory: ./frontend
        run: npm run lint
