name: Check JavaScript Linting
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "frontend/**/*.ts"
      - "frontend/**/*.tsx"
      - "frontend/**/*.js"
      - "frontend/**/*.jsx"
      - "frontend/**/*.json"
      - ".github/workflows/check-javascript-lint.yaml"
jobs:
  check-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Run ESLint
        working-directory: ./frontend
        run: npm run lint
