name: Check JavaScript Tests
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "frontend/**/*.ts"
      - "frontend/**/*.tsx"
      - "frontend/**/*.js"
      - "frontend/**/*.jsx"
      - "frontend/**/*.json"
      - ".github/workflows/check-javascript-tests.yaml"
jobs:
  check-tests:
    runs-on: ubuntu-latest
    container: node:22-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Run Vitest
        working-directory: ./frontend
        run: npm run test
