name: Deploy Backend
on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "!**/*.md"
      - "!.env.dist"
jobs:
  deploy-backend-to-flyio:
    name: Deploy Backend to Fly.io
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Run Flyctl
        working-directory: ./backend
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
