name: Format Python
on:
  push:
    paths:
      - "**/*.py"
  pull_request:
    paths:
      - "**/*.py"
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Run black
        working-directory: ./backend
        run: black --check .
