name: Test Python
on: [push, pull_request]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -r backend/requirements-dev.txt
      - name: Run tests
        working-directory: ./backend
        env:
          PYTHONPATH: backend
          CI: true
          DJANGO_SETTINGS_MODULE: travel_stream.settings
        run: pytest --color=yes
